export const categoriesConstants = {
    GET_CATEGORY_TREE: 'GET_CATEGORY_TREE',
    DELETE_SUCCESS: 'DELETE_SUCCESS',
    CATEGORY_PARENT_POST: 'CATEGORY_PARENT_POST',
    CATEGORY_PARENT_CATEGORY: 'CATEGORY_PARENT_CATEGORY'
}